eureka:
  client:
    serviceUrl:
      defaultZone: http://root:s3cr3t@localhost:8761/eureka/
management:
  security:
    enabled: false
server:
  port: 8082
spring:
  boot:
    admin:
      url: http://localhost:8762
user:
  role: Developer
