eureka:
  client:
    serviceUrl:
      defaultZone: http://root:s3cr3t@localhost:8761/eureka/
management:
  context-path: /manage
  security:
    enabled: false
feign:
  hystrix:
    enabled: true
server:
  port: 8083
spring:
  boot:
    admin:
      client:
        url: http://localhost:8762