eureka:
  client:
    serviceUrl:
      defaultZone: http://root:s3cr3t@localhost:8761/eureka/
  instance:
    metadata-map:
      management.port: ${management.port:8081}
      context-path: /manage
    health-check-url-path: /manage/health
management:
  context-path: /manage
  security:
    enabled: false
feign:
  hystrix:
    enabled: true
server:
  port: 8081
spring:
  boot:
    admin:
      url: http://localhost:8762